/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package isel.mpd.painter1.app;

import isel.mpd.painter1.view.PainterFrame;

public class App {

    public static void main(String[] args) {
        App app = new App();
        PainterFrame painter = new PainterFrame(app);

        painter.setVisible(true);
    }
}
